language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

install:
    - composer install --prefer-dist

script:
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=array
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetch
    - PATH=$PATH:$(pwd)/bin vendor/bin/phpbench run --report=default --group=fetchAll